using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using System.Xml;
using System.Xml.Linq;

namespace BbQ.Outcome.SourceGenerators;

/// <summary>Generates error helpers and transport-neutral catalogs from annotated enums.</summary>
[Generator]
public sealed class OutcomeSourceGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidDefinition = new(
        "BBQOUT001", "Invalid error definition", "{0}", "BbQ.Outcome",
        DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var enums = context.SyntaxProvider.ForAttributeWithMetadataName(
            "BbQ.Outcome.QbqOutcomeAttribute",
            static (node, _) => node is EnumDeclarationSyntax,
            static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);
        context.RegisterSourceOutput(enums, static (ctx, symbol) => Generate(ctx, symbol));
    }

    private static void Generate(SourceProductionContext context, INamedTypeSymbol symbol)
    {
        var names = new Stack<string>();
        var publiclyAccessible = true;
        for (INamedTypeSymbol? type = symbol; type != null; type = type.ContainingType)
        {
            if (type.Arity != 0 || (type.DeclaredAccessibility != Accessibility.Public &&
                type.DeclaredAccessibility != Accessibility.Internal &&
                type.DeclaredAccessibility != Accessibility.ProtectedOrInternal))
            {
                Report(context, symbol, "Generated error enums must be accessible outside their containing type and cannot be nested in a generic type.");
                return;
            }
            publiclyAccessible &= type.DeclaredAccessibility == Accessibility.Public;
            names.Push(type.Name);
        }

        var typeName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var helperName = string.Join("_", names) + "Errors";
        var members = symbol.GetMembers().OfType<IFieldSymbol>().Where(f => f.HasConstantValue).ToArray();
        var codes = new HashSet<string>(StringComparer.Ordinal);
        var values = new HashSet<object>();
        var definitions = new List<(IFieldSymbol Field, string Code, string Description, string Severity, string? Resource)>();
        foreach (var field in members)
        {
            var codeAttribute = Attribute(field, "BbQ.Outcome.ErrorCodeAttribute");
            var resourceAttribute = Attribute(field, "BbQ.Outcome.ErrorResourceKeyAttribute");
            var code = codeAttribute == null ? field.Name : StringArgument(codeAttribute);
            var resource = resourceAttribute == null ? null : StringArgument(resourceAttribute);
            if (string.IsNullOrWhiteSpace(code) || (resourceAttribute != null && string.IsNullOrWhiteSpace(resource)))
            {
                Report(context, field, "External error codes and explicitly provided resource keys must be nonblank strings.");
                return;
            }
            if (!codes.Add(code!))
            {
                Report(context, field, "External error codes must be unique within an error enum: " + code);
                return;
            }
            if (!values.Add(field.ConstantValue!))
            {
                Report(context, field, "Error enum aliases are ambiguous at runtime; each generated error must have a unique underlying value.");
                return;
            }
            var severityAttribute = Attribute(field, "BbQ.Outcome.ErrorSeverityAttribute");
            var severity = severityAttribute == null
                ? "global::BbQ.Outcome.ErrorSeverity.Error"
                : "(global::BbQ.Outcome.ErrorSeverity)" + Convert.ToInt32(severityAttribute.ConstructorArguments[0].Value, CultureInfo.InvariantCulture).ToString(CultureInfo.InvariantCulture);
            definitions.Add((field, code!, Description(field), severity, resource));
        }

        var errorType = "global::BbQ.Outcome.Error<" + typeName + ">";
        var sb = new StringBuilder("// <auto-generated />\n#nullable enable\n");
        if (!symbol.ContainingNamespace.IsGlobalNamespace)
            sb.Append("namespace ").Append(symbol.ContainingNamespace.ToDisplayString()).AppendLine(" {");
        sb.Append(publiclyAccessible ? "public" : "internal").Append(" static class ").Append(helperName).AppendLine(" {");
        foreach (var definition in definitions)
        {
            sb.Append("public static ").Append(errorType).Append(' ').Append(definition.Field.Name).Append("Error => new ")
                .Append(errorType).Append('(').Append(typeName).Append(".@").Append(definition.Field.Name)
                .Append(", ").Append(Literal(definition.Description)).Append(", ").Append(definition.Severity).AppendLine(");");
        }
        sb.Append("public static global::System.Collections.Generic.IReadOnlyList<").Append(errorType)
            .Append("> All { get; } = global::System.Array.AsReadOnly(new ").Append(errorType).AppendLine("[] {");
        foreach (var definition in definitions)
            sb.Append(definition.Field.Name).AppendLine("Error,");
        sb.AppendLine("});");
        sb.Append("public static global::BbQ.Outcome.ErrorDescriptor Describe(").Append(typeName).AppendLine(" code) => code switch {");
        foreach (var definition in definitions)
        {
            sb.Append(typeName).Append(".@").Append(definition.Field.Name)
                .Append(" => new global::BbQ.Outcome.ErrorDescriptor(")
                .Append(Literal(definition.Code)).Append(", ").Append(Literal(definition.Description))
                .Append(", ").Append(definition.Severity).Append(", ResourceKey: ")
                .Append(definition.Resource == null ? "null" : Literal(definition.Resource)).AppendLine("),");
        }
        sb.AppendLine("_ => throw new global::System.ArgumentOutOfRangeException(nameof(code), code, \"Unknown error code.\")\n};");
        sb.Append("public static global::BbQ.Outcome.IErrorDescriptorProvider<").Append(errorType)
            .Append("> DescriptorProvider { get; } = new global::BbQ.Outcome.DelegateErrorDescriptorProvider<")
            .Append(errorType).AppendLine(">(error => Describe(error.Code) with { Description = error.Description, Severity = error.Severity });");
        sb.AppendLine("}");
        if (!symbol.ContainingNamespace.IsGlobalNamespace)
            sb.AppendLine("}");

        // Reversible UTF-8 identity avoids namespace/underscore replacement collisions.
        var hint = BitConverter.ToString(Encoding.UTF8.GetBytes(typeName)).Replace("-", "") + ".Errors.g.cs";
        context.AddSource(hint, sb.ToString());
    }

    private static AttributeData? Attribute(IFieldSymbol field, string name)
        => field.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == name);

    private static string? StringArgument(AttributeData attribute)
        => attribute.ConstructorArguments.Length == 0 ? null : attribute.ConstructorArguments[0].Value as string;

    private static string Description(IFieldSymbol field)
    {
        var attribute = Attribute(field, "System.ComponentModel.DescriptionAttribute");
        if (attribute != null)
            return StringArgument(attribute) ?? field.Name;
        var xml = field.GetDocumentationCommentXml();
        if (!string.IsNullOrWhiteSpace(xml))
        {
            try
            {
                var summary = XElement.Parse(xml).Element("summary")?.Value;
                if (!string.IsNullOrWhiteSpace(summary))
                    return Regex.Replace(summary!, @"\s+", " ").Trim();
            }
            catch (XmlException) { /* Invalid documentation falls back to the member name. */ }
        }
        return field.Name;
    }

    private static string Literal(string value)
        => Microsoft.CodeAnalysis.CSharp.SymbolDisplay.FormatLiteral(value, quote: true);

    private static void Report(SourceProductionContext context, ISymbol symbol, string message)
        => context.ReportDiagnostic(Diagnostic.Create(InvalidDefinition, symbol.Locations.FirstOrDefault(), message));
}
