using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BbQ.Cqrs.SourceGenerators;

/// <summary>Emits opt-in, closed validation registrations only when the optional integration is present.</summary>
[Generator]
public sealed class OutcomeValidationRegistrationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
            static (node, _) => node is TypeDeclarationSyntax,
            static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((TypeDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol != null).Collect();
        context.RegisterSourceOutput(candidates.Combine(context.CompilationProvider),
            static (ctx, input) => Generate(ctx, input.Left, input.Right));
    }

    private static void Generate(SourceProductionContext context,
        System.Collections.Immutable.ImmutableArray<INamedTypeSymbol?> candidates, Compilation compilation)
    {
        if (compilation.GetTypeByMetadataName("BbQ.Cqrs.Validation.ValidationBehavior`2") == null)
            return;

        var types = new Dictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
        foreach (var candidate in candidates)
        {
            if (candidate == null || candidate.IsAbstract || !Accessible(candidate))
                continue;
            types[candidate.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)] = candidate;
        }
        var assembly = new string((compilation.AssemblyName ?? "Application").Where(char.IsLetterOrDigit).ToArray());
        if (assembly.Length == 0 || char.IsDigit(assembly[0])) assembly = "Assembly" + assembly;
        var method = "Add" + assembly + "OutcomeValidation";
        var sb = new StringBuilder("// <auto-generated />\n#nullable enable\nnamespace Microsoft.Extensions.DependencyInjection {\n");
        sb.Append("public static class ").Append(assembly).AppendLine("OutcomeValidationRegistration {");
        sb.Append("public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection ").Append(method)
            .AppendLine("(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services) {");
        sb.AppendLine("if (services is null) throw new global::System.ArgumentNullException(nameof(services));");
        var factories = new HashSet<string>(StringComparer.Ordinal);
        foreach (var pair in types.OrderBy(pair => pair.Key, StringComparer.Ordinal))
        {
            foreach (var iface in pair.Value.AllInterfaces)
            {
                if (pair.Value.TypeKind == TypeKind.Class && IsContract(iface, "BbQ.Cqrs.Validation", "IRequestValidator`1"))
                {
                    var service = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    RegisterEnumerable(sb, service, pair.Key);
                }
                if (!IsContract(iface, "BbQ.Cqrs", "IRequest`1") ||
                    iface.TypeArguments.Length != 1 || iface.TypeArguments[0] is not INamedTypeSymbol response ||
                    response.Name != "Outcome" || response.ContainingNamespace.ToDisplayString() != "BbQ.Outcome" ||
                    (response.Arity != 1 && response.Arity != 2))
                    continue;
                var responseName = response.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var arguments = string.Join(", ", response.TypeArguments.Select(type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)));
                if (factories.Add(responseName))
                {
                    sb.Append("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::BbQ.Cqrs.Validation.IValidationFailureFactory<")
                        .Append(responseName).Append(">, global::BbQ.Cqrs.Validation.OutcomeValidationFailureFactory<")
                        .Append(arguments).AppendLine(">>(services);");
                }
                if (response.Arity == 2 && response.TypeArguments[1].ToDisplayString() == "BbQ.Cqrs.Validation.ValidationIssue")
                    sb.AppendLine("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::BbQ.Cqrs.Validation.IValidationIssueMapper<global::BbQ.Cqrs.Validation.ValidationIssue>, global::BbQ.Cqrs.Validation.IdentityValidationIssueMapper>(services);");
                RegisterEnumerable(sb, "global::BbQ.Cqrs.IPipelineBehavior<" + pair.Key + ", " + responseName + ">",
                    "global::BbQ.Cqrs.Validation.ValidationBehavior<" + pair.Key + ", " + responseName + ">");
            }
        }
        sb.AppendLine("return services;\n}\n}\n}");
        context.AddSource(assembly + ".OutcomeValidationRegistration.g.cs", sb.ToString());
    }

    private static bool IsContract(INamedTypeSymbol symbol, string containingNamespace, string metadataName)
        => symbol.OriginalDefinition.MetadataName == metadataName &&
            symbol.ContainingNamespace.ToDisplayString() == containingNamespace;

    private static bool Accessible(INamedTypeSymbol symbol)
    {
        for (var type = symbol; type != null; type = type.ContainingType)
            if (type.Arity != 0 || (type.DeclaredAccessibility != Accessibility.Public &&
                type.DeclaredAccessibility != Accessibility.Internal))
                return false;
        return true;
    }

    private static void RegisterEnumerable(StringBuilder sb, string service, string implementation)
    {
        sb.Append("global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(services, global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<")
            .Append(service).Append(", ").Append(implementation).AppendLine(">());");
    }
}
